// Meme banks. The judgment pass picks a TIER + a rating; the server picks a
// line from the matching bank. Inference details never leave the server — the
// client only ever sees these curated strings.

export type TierKey =
  | "GIGACHAD_SCRAMBLE"
  | "CERTIFIED_COOKER"
  | "MID"
  | "NPC_CHAOS"
  | "TOUCH_GRASS";

export const TIERS: Record<
  TierKey,
  { label: string; emoji: string; color: string }
> = {
  GIGACHAD_SCRAMBLE: { label: "GIGACHAD SCRAMBLE", emoji: "🗿", color: "text-amber-400" },
  CERTIFIED_COOKER: { label: "CERTIFIED COOKER", emoji: "👨‍🍳", color: "text-emerald-400" },
  MID: { label: "CERTIFIED MID", emoji: "😐", color: "text-sky-400" },
  NPC_CHAOS: { label: "NPC ENERGY", emoji: "🤖", color: "text-zinc-400" },
  TOUCH_GRASS: { label: "GO TOUCH GRASS", emoji: "🌿", color: "text-lime-400" },
};

export const ROASTS: Record<TierKey, string[]> = {
  GIGACHAD_SCRAMBLE: [
    "bro scrambled like his life depended on it 🗿 absolute cinema",
    "this scramble goes HARD. Jev had to lock in for this one",
    "certified menaces were invented for scrambles like this",
    "NO way a human just did that. sigma scramble detected",
  ],
  CERTIFIED_COOKER: [
    "you cooked. mildly. the kitchen is still standing 👨‍🍳",
    "let him COOK — the cube is now officially in the danger zone",
    "decent chaos. your grandma would be concerned, Jev is impressed",
    "this scramble slaps harder than monday morning",
  ],
  MID: [
    "the scramble is mid. the cube is yawning 😐",
    "Jev has seen this one. it's the same in every timeline",
    "you call that chaos? my wifi buffer has more twists",
    "NPC-tier effort but the vibe is salvageable",
  ],
  NPC_CHAOS: [
    "bro really pressed buttons like an NPC in a 2010 mobile ad 🤖",
    "this scramble was generated by pure vibes and zero malice",
    "the cube is barely inconvenienced. Jev is barely awake",
    "skibidi-tier scramble. Touch some corners of the map maybe",
  ],
  TOUCH_GRASS: [
    "this is barely a scramble. go outside. the grass misses you 🌿",
    "Jev solved this before you finished pressing the button",
    "the cube scrambled itself out of second-hand embarrassment",
    "maximum mid. the algorithm is disappointed but not surprised",
  ],
};

export const HYPE_LINES = [
  "Jev is locking in 🔒",
  "reading the chaos...",
  "big brain mode: ACTIVATED 🧠",
  "calculating 43 quintillion positions...",
  "vibes checked. cube measured.",
];

// Jev's toolbox. The agent loop offers these every step; the engine picks one
// and the server executes it against the live cube state. Keys stream to the
// client, which renders them from this table — no raw inference leaves home.
export type ToolKey =
  | "cross:swift" | "cross:grind"
  | "corner:0" | "corner:1" | "corner:2" | "corner:3"
  | "edge:0" | "edge:1" | "edge:2" | "edge:3"
  | "top:cross" | "top:edges" | "top:corners"
  | "speedrun" | "rewind";

export const JEV_TOOLS: Record<
  ToolKey,
  { label: string; emoji: string; feed: string; choice: string }
> = {
  "cross:swift": { label: "SWIFT CROSS", emoji: "🧱", feed: "building the cross — the fast way", choice: "Build the bottom cross, optimally." },
  "cross:grind": { label: "GRIND CROSS", emoji: "🧱", feed: "building the cross, quarter-turn grind", choice: "Build the bottom cross the grindy human way (quarter turns only)." },
  "corner:0": { label: "SEAT FRONT-RIGHT CORNER", emoji: "🧩", feed: "seating the FRONT-RIGHT corner", choice: "Seat the FRONT-RIGHT bottom corner." },
  "corner:1": { label: "SEAT FRONT-LEFT CORNER", emoji: "🧩", feed: "seating the FRONT-LEFT corner", choice: "Seat the FRONT-LEFT bottom corner." },
  "corner:2": { label: "SEAT BACK-LEFT CORNER", emoji: "🧩", feed: "seating the BACK-LEFT corner", choice: "Seat the BACK-LEFT bottom corner." },
  "corner:3": { label: "SEAT BACK-RIGHT CORNER", emoji: "🧩", feed: "seating the BACK-RIGHT corner", choice: "Seat the BACK-RIGHT bottom corner." },
  "edge:0": { label: "THREAD FRONT-RIGHT EDGE", emoji: "🔗", feed: "threading the FRONT-RIGHT middle edge", choice: "Thread the FRONT-RIGHT middle edge." },
  "edge:1": { label: "THREAD FRONT-LEFT EDGE", emoji: "🔗", feed: "threading the FRONT-LEFT middle edge", choice: "Thread the FRONT-LEFT middle edge." },
  "edge:2": { label: "THREAD BACK-LEFT EDGE", emoji: "🔗", feed: "threading the BACK-LEFT middle edge", choice: "Thread the BACK-LEFT middle edge." },
  "edge:3": { label: "THREAD BACK-RIGHT EDGE", emoji: "🔗", feed: "threading the BACK-RIGHT middle edge", choice: "Thread the BACK-RIGHT middle edge." },
  "top:cross": { label: "TOP CROSS", emoji: "✚", feed: "making the top cross", choice: "Orient the top edges into a cross." },
  "top:edges": { label: "MATCH TOP EDGES", emoji: "🔁", feed: "matching the top edges to the sides", choice: "Permute the top edges to match the side centers." },
  "top:corners": { label: "FINISH TOP CORNERS", emoji: "🎯", feed: "finishing the top corners", choice: "Position, orient, and finish the top corners." },
  speedrun: { label: "SPEEDRUN", emoji: "⚡", feed: "going superhuman — near-optimal finish", choice: "Go superhuman: finish the whole cube near-optimally." },
  rewind: { label: "REWIND", emoji: "⏪", feed: "got lazy — brute undo (should not happen)", choice: "" },
};

export type Rank = { name: string; minXp: number; emoji: string };

export const RANKS: Rank[] = [
  { name: "NPC", minXp: 0, emoji: "🤖" },
  { name: "MID SCRAMBLER", minXp: 150, emoji: "😐" },
  { name: "CERTIFIED COOK", minXp: 400, emoji: "👨‍🍳" },
  { name: "GIGACHAD", minXp: 900, emoji: "🗿" },
  { name: "SIGMA ORCHESTRATOR", minXp: 1600, emoji: "🕶️" },
];

export function rankFor(xp: number): { rank: Rank; next: Rank | null } {
  let idx = 0;
  for (let i = 0; i < RANKS.length; i++) if (xp >= RANKS[i].minXp) idx = i;
  return { rank: RANKS[idx], next: RANKS[idx + 1] ?? null };
}

export const BADGES = {
  first_blood: { label: "First Blood", emoji: "🩸", desc: "Let Jev solve your first scramble" },
  gigachad_scramble: { label: "Gigachad Scrambler", emoji: "🗿", desc: "Get a GIGACHAD tier rating" },
  chaos_agent: { label: "Chaos Agent", emoji: "🌪️", desc: "25+ move scramble solved" },
  speedrun: { label: "Speedrun Any%", emoji: "⚡", desc: "Watch a full solve without skipping" },
  sigma: { label: "Sigma Orbiter", emoji: "🕶️", desc: "Reach Sigma Orchestrator rank" },
} as const;

export type BadgeKey = keyof typeof BADGES;
