// Meme banks. The judgment pass picks a TIER + a rating; the server picks a
// line from the matching bank. Inference details never leave the server — the
// client only ever sees these curated strings.

export type TierKey =
  | "GIGACHAD_SCRAMBLE"
  | "CERTIFIED_COOKER"
  | "MID"
  | "NPC_CHAOS"
  | "TOUCH_GRASS";

export const TIERS: Record<
  TierKey,
  { label: string; emoji: string; color: string }
> = {
  GIGACHAD_SCRAMBLE: { label: "GIGACHAD SCRAMBLE", emoji: "🗿", color: "text-amber-400" },
  CERTIFIED_COOKER: { label: "CERTIFIED COOKER", emoji: "👨‍🍳", color: "text-emerald-400" },
  MID: { label: "CERTIFIED MID", emoji: "😐", color: "text-sky-400" },
  NPC_CHAOS: { label: "NPC ENERGY", emoji: "🤖", color: "text-zinc-400" },
  TOUCH_GRASS: { label: "GO TOUCH GRASS", emoji: "🌿", color: "text-lime-400" },
};

export const ROASTS: Record<TierKey, string[]> = {
  GIGACHAD_SCRAMBLE: [
    "bro scrambled like his life depended on it 🗿 absolute cinema",
    "this scramble goes HARD. Jev had to lock in for this one",
    "certified menaces were invented for scrambles like this",
    "NO way a human just did that. sigma scramble detected",
  ],
  CERTIFIED_COOKER: [
    "you cooked. mildly. the kitchen is still standing 👨‍🍳",
    "let him COOK — the cube is now officially in the danger zone",
    "decent chaos. your grandma would be concerned, Jev is impressed",
    "this scramble slaps harder than monday morning",
  ],
  MID: [
    "the scramble is mid. the cube is yawning 😐",
    "Jev has seen this one. it's the same in every timeline",
    "you call that chaos? my wifi buffer has more twists",
    "NPC-tier effort but the vibe is salvageable",
  ],
  NPC_CHAOS: [
    "bro really pressed buttons like an NPC in a 2010 mobile ad 🤖",
    "this scramble was generated by pure vibes and zero malice",
    "the cube is barely inconvenienced. Jev is barely awake",
    "skibidi-tier scramble. Touch some corners of the map maybe",
  ],
  TOUCH_GRASS: [
    "this is barely a scramble. go outside. the grass misses you 🌿",
    "Jev solved this before you finished pressing the button",
    "the cube scrambled itself out of second-hand embarrassment",
    "maximum mid. the algorithm is disappointed but not surprised",
  ],
};

export const HYPE_LINES = [
  "Jev is locking in 🔒",
  "reading the chaos...",
  "big brain mode: ACTIVATED 🧠",
  "calculating 43 quintillion positions...",
  "vibes checked. cube measured.",
];

export type Rank = { name: string; minXp: number; emoji: string };

export const RANKS: Rank[] = [
  { name: "NPC", minXp: 0, emoji: "🤖" },
  { name: "MID SCRAMBLER", minXp: 150, emoji: "😐" },
  { name: "CERTIFIED COOK", minXp: 400, emoji: "👨‍🍳" },
  { name: "GIGACHAD", minXp: 900, emoji: "🗿" },
  { name: "SIGMA ORCHESTRATOR", minXp: 1600, emoji: "🕶️" },
];

export function rankFor(xp: number): { rank: Rank; next: Rank | null } {
  let idx = 0;
  for (let i = 0; i < RANKS.length; i++) if (xp >= RANKS[i].minXp) idx = i;
  return { rank: RANKS[idx], next: RANKS[idx + 1] ?? null };
}

export const BADGES = {
  first_blood: { label: "First Blood", emoji: "🩸", desc: "Let Jev solve your first scramble" },
  gigachad_scramble: { label: "Gigachad Scrambler", emoji: "🗿", desc: "Get a GIGACHAD tier rating" },
  chaos_agent: { label: "Chaos Agent", emoji: "🌪️", desc: "25+ move scramble solved" },
  speedrun: { label: "Speedrun Any%", emoji: "⚡", desc: "Watch a full solve without skipping" },
  sigma: { label: "Sigma Orbiter", emoji: "🕶️", desc: "Reach Sigma Orchestrator rank" },
} as const;

export type BadgeKey = keyof typeof BADGES;
